[metadata]
name = lightthecandle
version = 0.1.2
description = A local-first software delivery control plane.

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.9
include_package_data = True

[options.packages.find]
where = src

[options.package_data]
lightthecandle =
    policies/*.json

[options.entry_points]
console_scripts =
    lightthecandle = lightthecandle.cli:main
